spring.application.name=AUTH-SERVICE
server.port=****

spring.datasource.driver-class-name=org.postgresql.Driver
spring.datasource.url=databaseurl
spring.datasource.username=username
spring.datasource.password=password

spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true

eureka.client.service-url.defaultZone=url2
eureka.instance.prefer-ip-address=true
eureka.instance.hostname=localhost
eureka.instance.non-secure-port=****
eureka.instance.instance-id=${spring.application.name}:${server.port}

# JWT secret key — change this to a long random string in production!
jwt.secret=somelongstring
jwt.expiration=****
