spring.application.name=AUTH-SERVICE
server.port=8082

spring.datasource.driver-class-name=org.postgresql.Driver
spring.datasource.url=jdbc:postgresql://localhost:5432/questiondb
spring.datasource.username=postgres
spring.datasource.password=711231

spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true

eureka.client.service-url.defaultZone=http://localhost:8761/eureka/
eureka.instance.prefer-ip-address=true
eureka.instance.hostname=localhost
eureka.instance.non-secure-port=8082
eureka.instance.instance-id=${spring.application.name}:${server.port}

# JWT secret key — change this to a long random string in production!
jwt.secret=MySuperSecretKeyForJWTTokenGenerationThatIsLongEnough1234567890
jwt.expiration=86400000
