server.port=8765
spring.application.name=Api_Gateway

# Eureka
eureka.client.service-url.defaultZone=http://localhost:8761/eureka/
eureka.instance.prefer-ip-address=true
eureka.instance.hostname=localhost
eureka.instance.instance-id=${spring.application.name}:${server.port}

# ? Question Service Route
spring.cloud.gateway.mvc.routes[0].id=question-service
spring.cloud.gateway.mvc.routes[0].uri=lb://QUESTION-SERVICE
spring.cloud.gateway.mvc.routes[0].predicates[0]=Path=/question/**

# ? Quiz Service Route
spring.cloud.gateway.mvc.routes[1].id=quiz-service
spring.cloud.gateway.mvc.routes[1].uri=lb://QUIZ-SERVICE
spring.cloud.gateway.mvc.routes[1].predicates[0]=Path=/quiz/**

